// generated by Fast Light User Interface Designer (fluid) version 1.0107

#ifndef frmMainDisplayUI_h
#define frmMainDisplayUI_h
#include <FL/Fl.H>
#include <FL/Fl_Gl_Window.H>
#include "apputil/eventballfltk.h"

class GLDisplay : public Fl_Gl_Window {
  void _GLDisplay();
public:
  GLDisplay(int X, int Y, int W, int H, const char *L = 0);
  GLDisplay(int W, int H, const char *L = 0);
  int handle(int event);
  void draw(void);
};
#include <FL/Fl_Group.H>

class MsgGroupUI : public Fl_Group {
public:
  MsgGroupUI(int X, int Y, int W, int H, const char *L = 0);
  int handle(int event);
};
class frmMainDisplay;
#include <FL/Fl_Double_Window.H>
#include <iostream>
#include <FL/Fl_Help_Dialog.h>
#include "dispview.h"
#include <FL/Fl_Menu_Bar.H>
#include <FL/Fl_Menu_Button.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Box.H>
#include <FL/Fl_Text_Display.H>

class MainDisplay {
  public:;
  frmMainDisplay *frmmaindisplay;
  MainDisplay(frmMainDisplay *v);
  Fl_Double_Window *mainwnd;
  Fl_Menu_Bar *mainmenu;
  static Fl_Menu_Item menu_mainmenu[];
  static Fl_Menu_Item *menu_main;
  static Fl_Menu_Item *menu_new;
  static Fl_Menu_Item *menu_openproject;
  static Fl_Menu_Item *menu_saveproject;
  static Fl_Menu_Item *menu_saveproject_as;
  static Fl_Menu_Item *menu_exit;
  static Fl_Menu_Item *menu_help;
  static Fl_Menu_Item *menu_about;
  Fl_Menu_Button *popup;
  static Fl_Menu_Item menu_popup[];
  MsgGroupUI *msggroupui;
  GLDisplay *output;
  Fl_Double_Window *aboutwnd;
  Fl_Box *aboutwndbox;
  Fl_Button *btn_about_close;
  Fl_Box *build;
  Fl_Double_Window *msgwnd;
  Fl_Text_Display *msgdsp;
  Fl_Button *btn_msgwnd_close;
  Fl_Text_Buffer msgtb;
  Fl_Help_Dialog help;
};
//header for sourcefile
#include "eventhnd.h"
//end of headers
#endif
