// generated by Fast Light User Interface Designer (fluid) version 1.0107

#ifndef frmMattingUI_h
#define frmMattingUI_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Round_Button.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Output.H>
#include <FL/Fl_Box.H>
#include <Fl/Fl_Float_Input.h>

class frmMattingUI {
public:
  public:;
  frmMattingUI();
  Fl_Double_Window *pnl;
  Fl_Round_Button *image_off;
  Fl_Round_Button *image_albedo;
  Fl_Round_Button *image_image;
  Fl_Round_Button *shape_off;
  Fl_Round_Button *shape_notex;
  Fl_Round_Button *shape_albedo;
  Fl_Round_Button *shape_image;
  Fl_Button *img1;
  Fl_Button *img2;
  Fl_Button *img3;
  Fl_Button *img4;
  Fl_Output *imagefile;
  Fl_Button *imagefile_dlg;
  Fl_Float_Input *norm_x;
  Fl_Float_Input *norm_y;
  Fl_Float_Input *norm_z;
  Fl_Button *reset_shape_btn;
  Fl_Button *build_shape_btn;
};
#endif
