// generated by Fast Light User Interface Designer (fluid) version 1.0107

#ifndef frmPrjTreeUI_h
#define frmPrjTreeUI_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FLU/Flu_Tree_Browser.h>

class frmPrjTreeUI {
  public:;
  ~frmPrjTreeUI();
  Fl_Double_Window* Init();
  Fl_Double_Window *main;
  Flu_Tree_Browser *tree;
};
#endif
