// generated by Fast Light User Interface Designer (fluid) version 1.0107

#ifndef frmSurfCtrlUI_h
#define frmSurfCtrlUI_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Box.H>
#include <FL/Fl_Check_Button.H>
#include <FL/Fl_Button.H>

class frmSurfCtrlUI {
  public:;
  frmSurfCtrlUI();
  Fl_Double_Window *pnl;
  Fl_Check_Button *viewsurf_show;
  Fl_Check_Button *viewsurf_clipplane;
  Fl_Check_Button *viewsurf_norms;
  Fl_Check_Button *viewsurf_texture;
  Fl_Button *btn_slota;
  Fl_Button *btn_slotb;
  Fl_Button *btn_slotc;
  Fl_Button *btn_slotd;
  Fl_Button *btn_slote;
  Fl_Button *btn_slotf;
  void cb_btn_slotf_i(Fl_Button*, void*);
  static void cb_btn_slotf(Fl_Button*, void*);
  Fl_Button *btn_edit_slot_links;
};
#include <FL/Fl_File_Input.H>

class frmEditSlotLinks {
  public:;
  frmEditSlotLinks();
  Fl_Double_Window *pnl;
  Fl_File_Input *edit_slotfilea;
  Fl_Button *btn_slotfilea;
  Fl_File_Input *edit_slotfileb;
  Fl_Button *btn_slotfileb;
  Fl_File_Input *edit_slotfilec;
  Fl_Button *btn_slotfilec;
  Fl_File_Input *edit_slotfiled;
  Fl_Button *btn_slotfiled;
  Fl_File_Input *edit_slotfilee;
  Fl_Button *btn_slotfilee;
  Fl_File_Input *edit_slotfilef;
  Fl_Button *btn_slotfilef;
  Fl_Button *btn_editslots_close;
  Fl_File_Input *edit_surftxtrfile;
  Fl_Button *btn_surftxtrfile;
  Fl_File_Input *edit_surftxtrmapfile;
  Fl_Button *btn_surftxtrmapfile;
};
#endif
