// generated by Fast Light User Interface Designer (fluid) version 1.0107

#ifndef frmViewCtrlUI_h
#define frmViewCtrlUI_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Box.H>
#include <FL/Fl_Check_Button.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Choice.H>
#include <FL/Fl_Light_Button.H>

class frmViewCtrlUI {
  public:;
public:
  frmViewCtrlUI();
  Fl_Double_Window *pnl;
  Fl_Check_Button *backgrnd;
  Fl_Check_Button *showtool;
  Fl_Check_Button *drawsimple;
  Fl_Check_Button *orthoprojection;
  Fl_Button *zoom_plus;
  Fl_Button *zoom_minus;
  Fl_Choice *animmethod;
  static Fl_Menu_Item menu_animmethod[];
  Fl_Button *animstart;
  Fl_Check_Button *light1;
  Fl_Check_Button *light2;
  Fl_Light_Button *do_not_hide;
  Fl_Button *reset;
};
#endif
