// generated by Fast Light User Interface Designer (fluid) version 1.0107

#include "frmMattingUI.h"

frmMattingUI::frmMattingUI() {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = pnl = new Fl_Double_Window(185, 285, "Matting");
    w = o;
    o->box(FL_UP_BOX);
    o->user_data((void*)(this));
    o->align(FL_ALIGN_BOTTOM);
    { Fl_Group* o = show = new Fl_Group(5, 23, 170, 73, "Show");
      o->box(FL_PLASTIC_UP_FRAME);
      o->align(FL_ALIGN_TOP_LEFT);
      { Fl_Round_Button* o = show_off = new Fl_Round_Button(10, 26, 71, 18, "off");
        o->down_box(FL_ROUND_DOWN_BOX);
      }
      { Fl_Round_Button* o = show_src = new Fl_Round_Button(10, 42, 71, 19, "source");
        o->down_box(FL_ROUND_DOWN_BOX);
      }
      { Fl_Round_Button* o = show_src_matte = new Fl_Round_Button(10, 58, 71, 19, "source+matte");
        o->down_box(FL_ROUND_DOWN_BOX);
      }
      { Fl_Round_Button* o = show_matte = new Fl_Round_Button(10, 74, 71, 18, "matte");
        o->down_box(FL_ROUND_DOWN_BOX);
      }
      o->end();
    }
    { Fl_Output* o = imagefile_src = new Fl_Output(5, 115, 175, 20, "Source Image File:");
      o->align(FL_ALIGN_TOP_LEFT);
    }
    imagefiledlg_src = new Fl_Button(150, 135, 30, 25, "...");
    reset_btn = new Fl_Button(40, 245, 35, 25, "Rst");
    go_btn = new Fl_Button(110, 245, 35, 25, "@>");
    { Fl_Output* o = imagefile_matte = new Fl_Output(5, 175, 175, 20, "Matte Image File");
      o->align(FL_ALIGN_TOP_LEFT);
    }
    imagefiledlg_matte = new Fl_Button(150, 195, 30, 25, "...");
    o->end();
    o->resizable(o);
  }
}
