// generated by Fast Light User Interface Designer (fluid) version 1.0107

#ifndef frmMattingUI_h
#define frmMattingUI_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Round_Button.H>
#include <FL/Fl_Output.H>
#include <FL/Fl_Button.H>

class frmMattingUI {
public:
  public:;
  frmMattingUI();
  Fl_Double_Window *pnl;
  Fl_Group *show;
  Fl_Round_Button *show_off;
  Fl_Round_Button *show_src;
  Fl_Round_Button *show_src_matte;
  Fl_Round_Button *show_matte;
  Fl_Output *imagefile_src;
  Fl_Button *imagefiledlg_src;
  Fl_Button *reset_btn;
  Fl_Button *go_btn;
  Fl_Output *imagefile_matte;
  Fl_Button *imagefiledlg_matte;
};
#endif
