// generated by Fast Light User Interface Designer (fluid) version 1.0107

#include "frmMainDisplayUI.h"
GLDisplay::GLDisplay(int X, int Y, int W, int H, const char *L)
  : Fl_Gl_Window(X, Y, W, H, L) {
  _GLDisplay();
}

GLDisplay::GLDisplay(int W, int H, const char *L)
  : Fl_Gl_Window(0, 0, W, H, L) {
  clear_flag(16);
  _GLDisplay();
}

void GLDisplay::_GLDisplay() {
  GLDisplay *w = this;
  GLDisplay *o = this;
o->box(FL_FLAT_BOX);
o->color(FL_BACKGROUND_COLOR);
o->selection_color(FL_BACKGROUND_COLOR);
o->labeltype(FL_NO_LABEL);
o->labelfont(0);
o->labelsize(14);
o->labelcolor(FL_FOREGROUND_COLOR);
o->align(FL_ALIGN_CLIP|FL_ALIGN_INSIDE);
o->when(FL_WHEN_RELEASE);
clear_border();
end();
resizable(this);
}
MsgGroupUI::MsgGroupUI(int X, int Y, int W, int H, const char *L)
  : Fl_Group(0, 0, W, H, L) {
  MsgGroupUI *o = this;
o->box(FL_FLAT_BOX);
o->color(FL_BACKGROUND_COLOR);
o->selection_color(FL_BACKGROUND_COLOR);
o->labeltype(FL_NO_LABEL);
o->labelfont(0);
o->labelsize(14);
o->labelcolor(FL_FOREGROUND_COLOR);
o->align(FL_ALIGN_TOP);
o->when(FL_WHEN_RELEASE);
position(X, Y);
end();
}

Fl_Menu_Item MainDisplay::menu_mainmenu[] = {
 {"File", 0,  0, 0, 64, FL_NORMAL_LABEL, 0, 14, 0},
 {"New", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"Open Project", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"Save Project", 0x40073,  0, 0, 1, FL_NORMAL_LABEL, 0, 14, 0},
 {"Save Project As", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"Exit", 0x80071,  0, 0, 128, FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0},
 {"Help", 0,  0, 0, 64, FL_NORMAL_LABEL, 0, 14, 0},
 {"Help", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"About", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0},
 {0,0,0,0,0,0,0,0,0}
};
Fl_Menu_Item* MainDisplay::menu_main = MainDisplay::menu_mainmenu + 0;
Fl_Menu_Item* MainDisplay::menu_new = MainDisplay::menu_mainmenu + 1;
Fl_Menu_Item* MainDisplay::menu_openproject = MainDisplay::menu_mainmenu + 2;
Fl_Menu_Item* MainDisplay::menu_saveproject = MainDisplay::menu_mainmenu + 3;
Fl_Menu_Item* MainDisplay::menu_saveproject_as = MainDisplay::menu_mainmenu + 4;
Fl_Menu_Item* MainDisplay::menu_exit = MainDisplay::menu_mainmenu + 5;
Fl_Menu_Item* MainDisplay::menu_help = MainDisplay::menu_mainmenu + 8;
Fl_Menu_Item* MainDisplay::menu_about = MainDisplay::menu_mainmenu + 9;

Fl_Menu_Item MainDisplay::menu_popup[] = {
 {"item", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"item", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"item", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0}
};

MainDisplay::MainDisplay(frmMainDisplay *v) {
  Fl_Double_Window* w;
  frmmaindisplay = v;
  { Fl_Double_Window* o = mainwnd = new Fl_Double_Window(780, 550, "3D Zero Application  0.0.1");
    w = o;
    o->user_data((void*)(this));
    o->align(FL_ALIGN_CENTER);
    { Fl_Menu_Bar* o = mainmenu = new Fl_Menu_Bar(0, 0, 595, 25);
      o->menu(menu_mainmenu);
    }
    { Fl_Menu_Button* o = popup = new Fl_Menu_Button(50, 60, 15, 15);
      o->type(4);
      o->labeltype(FL_NO_LABEL);
      o->hide();
      o->menu(menu_popup);
    }
    { MsgGroupUI* o = msggroupui = new MsgGroupUI(595, 0, 185, 25);
      o->box(FL_UP_BOX);
      o->color(FL_BACKGROUND_COLOR);
      o->selection_color(FL_BACKGROUND_COLOR);
      o->labeltype(FL_NORMAL_LABEL);
      o->labelfont(0);
      o->labelsize(14);
      o->labelcolor(FL_FOREGROUND_COLOR);
      o->align(68|FL_ALIGN_INSIDE);
      o->when(FL_WHEN_RELEASE);
    }
    { Fl_Group* o = new Fl_Group(0, 25, 30, 525);
      new Fl_Button(0, 25, 30, 30);
      { Fl_Group* o = new Fl_Group(0, 405, 30, 145);
        o->end();
        Fl_Group::current()->resizable(o);
      }
      o->end();
    }
    { GLDisplay* o = output = new GLDisplay(30, 25, 750, 525);
      o->box(FL_NO_BOX);
      o->color(FL_BACKGROUND_COLOR);
      o->selection_color(FL_BACKGROUND_COLOR);
      o->labeltype(FL_NORMAL_LABEL);
      o->labelfont(0);
      o->labelsize(14);
      o->labelcolor(FL_FOREGROUND_COLOR);
      o->align(FL_ALIGN_CENTER);
      o->when(FL_WHEN_RELEASE);
      o->end();
      Fl_Group::current()->resizable(o);
    }
    o->end();
  }
  { Fl_Double_Window* o = aboutwnd = new Fl_Double_Window(360, 260, "About 3D Plastic Surgery Simulator 0.3.0");
    w = o;
    o->user_data((void*)(this));
    { Fl_Box* o = aboutwndbox = new Fl_Box(35, 25, 280, 25, "3D Zero Application ver. 0.1.0");
      o->labelfont(1);
    }
    new Fl_Box(30, 140, 295, 30, "Copyright 2005-2010 by Alex Blinov");
    btn_about_close = new Fl_Button(140, 210, 65, 25, "Close");
    { Fl_Box* o = new Fl_Box(35, 65, 295, 55, "This program is based  in part on the work of the FLTK project (http://www.fl\
tk.org).");
      o->align(FL_ALIGN_WRAP);
    }
    build = new Fl_Box(40, 170, 295, 30, "Build ");
    o->set_modal();
    o->end();
  }
  { Fl_Double_Window* o = msgwnd = new Fl_Double_Window(535, 350, "Message Log");
    w = o;
    o->user_data((void*)(this));
    msgdsp = new Fl_Text_Display(5, 5, 525, 310);
    btn_msgwnd_close = new Fl_Button(460, 320, 70, 25, "Close");
    o->end();
    o->resizable(o);
  }
}
//header for sourcefile
//end of headers
