// generated by Fast Light User Interface Designer (fluid) version 1.0107

#include "frmSurfCtrlUI.h"

void frmSurfCtrlUI::cb_btn_slotf_i(Fl_Button*, void*) {
  ;
}
void frmSurfCtrlUI::cb_btn_slotf(Fl_Button* o, void* v) {
  ((frmSurfCtrlUI*)(o->parent()->user_data()))->cb_btn_slotf_i(o,v);
}

frmSurfCtrlUI::frmSurfCtrlUI() {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = pnl = new Fl_Double_Window(175, 265);
    w = o;
    o->user_data((void*)(this));
    { Fl_Box* o = new Fl_Box(20, 10, 135, 80);
      o->box(FL_PLASTIC_UP_FRAME);
    }
    { Fl_Check_Button* o = viewsurf_show = new Fl_Check_Button(25, 20, 60, 15, "show");
      o->down_box(FL_DOWN_BOX);
    }
    { Fl_Check_Button* o = viewsurf_clipplane = new Fl_Check_Button(25, 35, 85, 15, "clip plane");
      o->down_box(FL_DOWN_BOX);
    }
    { Fl_Check_Button* o = viewsurf_norms = new Fl_Check_Button(25, 50, 120, 15, "norms smooth");
      o->down_box(FL_DOWN_BOX);
    }
    { Fl_Check_Button* o = viewsurf_texture = new Fl_Check_Button(25, 65, 120, 15, "texture");
      o->down_box(FL_DOWN_BOX);
    }
    { Fl_Box* o = new Fl_Box(20, 105, 135, 135);
      o->box(FL_PLASTIC_UP_FRAME);
    }
    btn_slota = new Fl_Button(35, 120, 45, 20, "slot A");
    btn_slotb = new Fl_Button(100, 120, 45, 20, "slot B");
    btn_slotc = new Fl_Button(35, 145, 45, 20, "slot C");
    btn_slotd = new Fl_Button(100, 145, 45, 20, "slot D");
    btn_slote = new Fl_Button(35, 170, 45, 20, "slot E");
    { Fl_Button* o = btn_slotf = new Fl_Button(100, 170, 45, 20, "slot F");
      o->callback((Fl_Callback*)cb_btn_slotf);
    }
    btn_edit_slot_links = new Fl_Button(30, 200, 115, 20, "Edit Slot Links");
    o->end();
    o->resizable(o);
  }
}

frmEditSlotLinks::frmEditSlotLinks() {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = pnl = new Fl_Double_Window(225, 345, "Edit Slot Links");
    w = o;
    o->user_data((void*)(this));
    edit_slotfilea = new Fl_File_Input(30, 15, 150, 30, "A");
    btn_slotfilea = new Fl_Button(185, 20, 25, 25, "...");
    edit_slotfileb = new Fl_File_Input(30, 45, 150, 30, "B:");
    btn_slotfileb = new Fl_Button(185, 50, 25, 25, "...");
    edit_slotfilec = new Fl_File_Input(30, 75, 150, 30, "C:");
    btn_slotfilec = new Fl_Button(185, 80, 25, 25, "...");
    edit_slotfiled = new Fl_File_Input(30, 105, 150, 30, "D:");
    btn_slotfiled = new Fl_Button(185, 110, 25, 25, "...");
    edit_slotfilee = new Fl_File_Input(30, 135, 150, 30, "E:");
    btn_slotfilee = new Fl_Button(185, 140, 25, 25, "...");
    edit_slotfilef = new Fl_File_Input(30, 165, 150, 30, "F:");
    btn_slotfilef = new Fl_Button(185, 170, 25, 25, "...");
    btn_editslots_close = new Fl_Button(75, 305, 80, 25, "Close");
    { Fl_File_Input* o = edit_surftxtrfile = new Fl_File_Input(15, 220, 165, 30, "Texture file:");
      o->align(FL_ALIGN_TOP_LEFT);
    }
    btn_surftxtrfile = new Fl_Button(185, 225, 25, 25, "...");
    { Fl_File_Input* o = edit_surftxtrmapfile = new Fl_File_Input(15, 265, 165, 30, "Texture mapping file:");
      o->align(FL_ALIGN_TOP_LEFT);
    }
    btn_surftxtrmapfile = new Fl_Button(185, 270, 25, 25, "...");
    o->set_modal();
    o->end();
    o->resizable(o);
  }
}
