// generated by Fast Light User Interface Designer (fluid) version 1.0107

#include "frmViewCtrlUI.h"

Fl_Menu_Item frmViewCtrlUI::menu_animmethod[] = {
 {"360 (0,1,0)", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"360(0,1,0.5)", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"left-right", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0}
};

frmViewCtrlUI::frmViewCtrlUI() {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = pnl = new Fl_Double_Window(185, 335);
    w = o;
    o->user_data((void*)(this));
    { Fl_Box* o = new Fl_Box(20, 25, 145, 80);
      o->box(FL_PLASTIC_UP_FRAME);
    }
    { Fl_Check_Button* o = backgrnd = new Fl_Check_Button(25, 35, 100, 15, "background");
      o->down_box(FL_DOWN_BOX);
    }
    { Fl_Check_Button* o = showtool = new Fl_Check_Button(25, 50, 95, 15, "show tools");
      o->down_box(FL_DOWN_BOX);
    }
    { Fl_Check_Button* o = drawsimple = new Fl_Check_Button(25, 65, 100, 15, "draw simple");
      o->down_box(FL_DOWN_BOX);
    }
    { Fl_Check_Button* o = orthoprojection = new Fl_Check_Button(25, 80, 125, 15, "orthogonal proj.");
      o->down_box(FL_DOWN_BOX);
    }
    { Fl_Box* o = new Fl_Box(20, 110, 145, 40, "Zoom:");
      o->box(FL_PLASTIC_UP_FRAME);
      o->align(FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
    }
    zoom_plus = new Fl_Button(110, 120, 20, 20, "-");
    zoom_minus = new Fl_Button(135, 120, 20, 20, "+");
    { Fl_Box* o = new Fl_Box(20, 155, 145, 70);
      o->box(FL_PLASTIC_UP_FRAME);
    }
    { Fl_Choice* o = animmethod = new Fl_Choice(35, 165, 115, 25);
      o->down_box(FL_BORDER_BOX);
      o->align(FL_ALIGN_CENTER|FL_ALIGN_INSIDE);
      o->menu(menu_animmethod);
    }
    animstart = new Fl_Button(95, 195, 55, 25, "Start");
    { Fl_Box* o = new Fl_Box(20, 230, 145, 70);
      o->box(FL_PLASTIC_UP_FRAME);
    }
    { Fl_Check_Button* o = light1 = new Fl_Check_Button(25, 240, 70, 20, "light 1");
      o->down_box(FL_DOWN_BOX);
    }
    { Fl_Check_Button* o = light2 = new Fl_Check_Button(25, 260, 75, 25, "light 2");
      o->down_box(FL_DOWN_BOX);
    }
    do_not_hide = new Fl_Light_Button(0, 0, 185, 20, "do not hide");
    reset = new Fl_Button(55, 310, 80, 20, "Reset");
    o->end();
    o->resizable(o);
  }
}
